[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "parsing_tokens"
version = "0.3.0"
description = "Text tokenization and parsing library (WIP)"
authors = [{name = "Antony"}]
readme = "README.md"
requires-python = ">=3.10"